### ISSUE TITLE
Evaulation graphs for DMC

### ISSUE THREAD

**Issue by vedantdave97** [kyonofx/tia#3]
Hello @kyonofx,
Thanks for the paper and the training/evaluation graphs.

In the google drive link provided, I can only find graphs for Dreamer in DMC environment. Can you please provide the graphs for TIA in the standard environment (no noise)? (I am talking about Figure 10, the blue plot with "no Bg")

If I am missing something, let me know.

**Comment by kyonofx** [comment]
Hi, 

The google drive folder contains metrics for TIA on the driving video tasks. We did not run experiments of TIA on clean environments (TIA will not help in clean environments).  Figure 10 reports the performance of Dreamer, for which all metrics are in the google drive.

**Comment by vedantdave97** [comment]
Hello,

Thanks for the quick response and clarification.
